/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Control;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import model.musics;

/**
 *
 * @author miaag
 */

public class Musicplay extends javax.swing.JPanel {

    /**
     * Creates new form Musicplay
     */
    
    Control remoteControl = new Control();
    //boolean playpic = false;
    boolean playpic = true;
    private PlayListener playslisten;
     ArrayList<musics> musicList;
     
     
    public Musicplay() {
        initComponents();
        jPanel3.setBackground(Color.BLACK);
        ImageIcon cokelabel = new ImageIcon("src/image/Spotiphy.png");
        Image img = cokelabel.getImage();
        Image scale = img.getScaledInstance(120, 120, Image.SCALE_SMOOTH);
        ImageIcon scaled = new ImageIcon(scale);
     //   jLabel1.setIcon(scaled);
        setBackground(new Color(0, 0, 0, 100));
        
        
           musicList = remoteControl.allMusics();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int countsmusic = remoteControl.getMusiccount();
        Object rowsdats[] = new Object[3];
        model.setRowCount(0);
        for(int i =0;i<=countsmusic;i++){
            
            rowsdats[0]= musicList.get(i).getTitle();
            rowsdats[1]= musicList.get(i).getArtist();
            rowsdats[2]= musicList.get(i).getGenre();
                    
            model.addRow(rowsdats);
        
        
    }
        
        
    }
    
    

    
    public static void main(String[] args) {
         java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
                new Musicplay().setVisible(true);
            }
       });
    }
  
    
     public void setPlayListener(PlayListener inputListener) {
       this.playslisten = inputListener;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lyrics = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        piclbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        artisitlbl = new javax.swing.JLabel();
        titlelbl = new javax.swing.JLabel();
        titlelbl1 = new javax.swing.JLabel();
        titlelbl3 = new javax.swing.JLabel();
        playbtn = new javax.swing.JLabel();
        backbtn = new javax.swing.JLabel();
        nextbtn = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        titlelbl2 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel4.setText("jLabel4");

        setBackground(new java.awt.Color(0, 0, 0));
        setOpaque(false);
        setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Playlist");
        add(jLabel3);
        jLabel3.setBounds(20, 1601, 55, 26);

        jPanel3.setLayout(null);

        jScrollPane2.setBorder(new javax.swing.border.MatteBorder(null));

        lyrics.setEditable(false);
        lyrics.setBackground(new java.awt.Color(0, 0, 0));
        lyrics.setColumns(20);
        lyrics.setFont(new java.awt.Font("Garamond", 0, 22)); // NOI18N
        lyrics.setForeground(new java.awt.Color(255, 255, 255));
        lyrics.setRows(5);
        lyrics.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(176, 0, 32), 3, true));
        lyrics.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(lyrics);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(320, 70, 410, 220);

        jPanel1.setBackground(new java.awt.Color(176, 0, 32));
        jPanel1.setLayout(null);

        piclbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pausevinyl.png"))); // NOI18N
        jPanel1.add(piclbl);
        piclbl.setBounds(-50, 20, 310, 237);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(20, 20, 270, 280);

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAlignmentX(1.0F);
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(2);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(320, 360, 410, 140);

        jPanel2.setBackground(new java.awt.Color(147, 112, 219));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        artisitlbl.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        artisitlbl.setForeground(new java.awt.Color(255, 255, 255));
        artisitlbl.setText("No Artist");
        jPanel2.add(artisitlbl, java.awt.BorderLayout.PAGE_END);

        titlelbl.setBackground(new java.awt.Color(255, 255, 255));
        titlelbl.setFont(new java.awt.Font("Garamond", 0, 27)); // NOI18N
        titlelbl.setForeground(new java.awt.Color(255, 255, 255));
        titlelbl.setText("No Music Playing                                                                     ");
        jPanel2.add(titlelbl, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(20, 319, 280, 70);

        titlelbl1.setBackground(new java.awt.Color(255, 255, 255));
        titlelbl1.setFont(new java.awt.Font("Garamond", 0, 27)); // NOI18N
        titlelbl1.setForeground(new java.awt.Color(255, 255, 255));
        titlelbl1.setText("Song Queue");
        jPanel3.add(titlelbl1);
        titlelbl1.setBounds(320, 310, 180, 32);

        titlelbl3.setBackground(new java.awt.Color(255, 255, 255));
        titlelbl3.setFont(new java.awt.Font("Garamond", 0, 27)); // NOI18N
        titlelbl3.setForeground(new java.awt.Color(255, 255, 255));
        titlelbl3.setText("Lyrics");
        jPanel3.add(titlelbl3);
        titlelbl3.setBounds(320, 30, 180, 32);

        playbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/play-48 (1).png"))); // NOI18N
        playbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playbtnMouseClicked(evt);
            }
        });
        jPanel3.add(playbtn);
        playbtn.setBounds(120, 410, 50, 60);

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/media-skip-backward-48 (1).png"))); // NOI18N
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        jPanel3.add(backbtn);
        backbtn.setBounds(50, 410, 50, 60);

        nextbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow-44-48 (1).png"))); // NOI18N
        nextbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextbtnMouseClicked(evt);
            }
        });
        jPanel3.add(nextbtn);
        nextbtn.setBounds(180, 410, 50, 60);

        jSlider1.setMaximum(6);
        jSlider1.setMinimum(-40);
        jSlider1.setOpaque(false);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel3.add(jSlider1);
        jSlider1.setBounds(30, 490, 200, 26);

        add(jPanel3);
        jPanel3.setBounds(0, 0, 750, 540);

        titlelbl2.setBackground(new java.awt.Color(255, 255, 255));
        titlelbl2.setFont(new java.awt.Font("Garamond", 0, 27)); // NOI18N
        titlelbl2.setForeground(new java.awt.Color(255, 255, 255));
        titlelbl2.setText("Song Queue");
        add(titlelbl2);
        titlelbl2.setBounds(320, 310, 180, 32);
    }// </editor-fold>//GEN-END:initComponents

    private void playbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playbtnMouseClicked
        // TODO add your handling code here:
        
        if(playpic){
            piclbl.setIcon(new ImageIcon("src/image/pausevinyl.png"));
            playbtn.setIcon(new ImageIcon("src/image/pause-48.png"));
            remoteControl.playmusic();
            piclbl.setIcon(new ImageIcon(remoteControl.PicFile()));
            titlelbl.setText(remoteControl.Title());
            artisitlbl.setText(remoteControl.Artistss());
            lyrics.setText(remoteControl.getLyrics());
            playpic = false;
        }
        
        else{
            playbtn.setIcon(new ImageIcon("src/image/play-48 (1).png"));
            remoteControl.playmusic();
            piclbl.setIcon(new ImageIcon(remoteControl.PicFile()));
            playpic = true;
        }
           //     MusicPlayerEvent ev =new MusicPlayerEvent(this, remoteControl.getLyrics());
                
          //      if(playslisten != null){
          //          playslisten.formEventOccurred(ev);
          //      }
    }//GEN-LAST:event_playbtnMouseClicked

    private void nextbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextbtnMouseClicked
        // TODO add your handling code here:
        
        if(playpic){
             playbtn.setIcon(new ImageIcon("src/image/pause-48.png"));
        }  
        
        remoteControl.NextMusic();
        String pics = remoteControl.PicFile();
        piclbl.setIcon(new ImageIcon(pics));
        titlelbl.setText(remoteControl.Title());
        artisitlbl.setText(remoteControl.Artistss());
        lyrics.setText(remoteControl.getLyrics());
  
       /*    MusicPlayerEvent ev =new MusicPlayerEvent(this, remoteControl.getLyrics());
                
                if(playslisten != null){
                    playslisten.formEventOccurred(ev);
                }*/
    }//GEN-LAST:event_nextbtnMouseClicked

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        // TODO add your handling code here:
        remoteControl.BackMusic();
        String pics = remoteControl.PicFile();
        piclbl.setIcon(new ImageIcon(pics));
        titlelbl.setText(remoteControl.Title());
        artisitlbl.setText(remoteControl.Artistss());
        lyrics.setText(remoteControl.getLyrics());
          
        /*MusicPlayerEvent ev =new MusicPlayerEvent(this, remoteControl.getLyrics());
                
                if(playslisten != null){
                    playslisten.formEventOccurred(ev);
                } */
    }//GEN-LAST:event_backbtnMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        int row=jTable1.rowAtPoint(evt.getPoint());
        System.out.println(row);
        remoteControl.setNewSong(true);
        remoteControl.setMusicindex(row);
        
        String pics = remoteControl.PicFile();

        
        remoteControl.playmusic();
        titlelbl.setText(remoteControl.Title());
        artisitlbl.setText(remoteControl.Artistss());
        String picss = remoteControl.PicFile();
        piclbl.setIcon(new ImageIcon(picss));
         
         
        /* MusicPlayerEvent ev =new MusicPlayerEvent(this, remoteControl.getLyrics());
                
                if(playslisten != null){
                    playslisten.formEventOccurred(ev);
                } */
    }//GEN-LAST:event_jTable1MouseClicked

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        remoteControl.changeVolume(jSlider1.getValue());

    }//GEN-LAST:event_jSlider1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artisitlbl;
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea lyrics;
    private javax.swing.JLabel nextbtn;
    private javax.swing.JLabel piclbl;
    private javax.swing.JLabel playbtn;
    private javax.swing.JLabel titlelbl;
    private javax.swing.JLabel titlelbl1;
    private javax.swing.JLabel titlelbl2;
    private javax.swing.JLabel titlelbl3;
    // End of variables declaration//GEN-END:variables
}
